-- AlterTable
ALTER TABLE `rate_configs`
    ADD COLUMN `multiStoreFeePerStore` DOUBLE NOT NULL DEFAULT 30,
    ADD COLUMN `maxAdditionalStores` INTEGER NOT NULL DEFAULT 2,
    ADD COLUMN `groceryFeeThreshold` DOUBLE NOT NULL DEFAULT 3000,
    ADD COLUMN `groceryFeePercent` DOUBLE NOT NULL DEFAULT 10,
    ADD COLUMN `groceryFeeFlat` DOUBLE NOT NULL DEFAULT 50,
    ADD COLUMN `nonCodThreshold` DOUBLE NOT NULL DEFAULT 3000,
    ADD COLUMN `nonCodFeeHigh` DOUBLE NOT NULL DEFAULT 50,
    ADD COLUMN `nonCodFeeLow` DOUBLE NOT NULL DEFAULT 15;
